### ISSUE TITLE
Interactive features missing

### ISSUE THREAD

**Issue by Achnos** [dstahlke/gnuplot-iostream#16]
Hello.

It would seem that when i plot using gnuplot-iostream from my C++ program, the interactive features of gnuplot are missing (thing such as zoom, and moving around etc.), is there a way to fix this? They are working from the command-line version og gnuplot.

Regards

**Comment by dstahlke** [comment]
Yes, this happens to me too sometimes. I'm not sure what exact 
circumstances cause this.  For me it only happens when the main program 
exits but gnuplot persists after (the gnuplot -persist option).  But 
sometimes interaction still works, sometimes it doesn't.  Can you try 
having your program not exit, and the Gnuplot object remain in scope?  
You can just wait for a keystroke with getchar() or something.  
Hopefully that fixes it.

- Dan

**Comment by Achnos** [comment]
Hi Dan.

That seems to be working for me.

Regards
